// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc0NZIXGC9LS4hNOPDe7RPP7qxn8mwsFI',
    appId: '1:263909690816:web:c6116835210ce10dedcc25',
    messagingSenderId: '263909690816',
    projectId: 'utilitybills-c942a',
    authDomain: 'utilitybills-c942a.firebaseapp.com',
    storageBucket: 'utilitybills-c942a.firebasestorage.app',
    measurementId: 'G-L6PQX41MQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6KqOSvmO3BJidgvhsfKVYXZykCAZ-zys',
    appId: '1:263909690816:android:2ca8f9500c1846c5edcc25',
    messagingSenderId: '263909690816',
    projectId: 'utilitybills-c942a',
    storageBucket: 'utilitybills-c942a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqOybeywKhJH5WvXmGArCI2mO7-BLrEnc',
    appId: '1:263909690816:ios:55189a1bbe91cc15edcc25',
    messagingSenderId: '263909690816',
    projectId: 'utilitybills-c942a',
    storageBucket: 'utilitybills-c942a.firebasestorage.app',
    iosBundleId: 'com.example.utilityBillsManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqOybeywKhJH5WvXmGArCI2mO7-BLrEnc',
    appId: '1:263909690816:ios:55189a1bbe91cc15edcc25',
    messagingSenderId: '263909690816',
    projectId: 'utilitybills-c942a',
    storageBucket: 'utilitybills-c942a.firebasestorage.app',
    iosBundleId: 'com.example.utilityBillsManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc0NZIXGC9LS4hNOPDe7RPP7qxn8mwsFI',
    appId: '1:263909690816:web:db7e33fba55d7f10edcc25',
    messagingSenderId: '263909690816',
    projectId: 'utilitybills-c942a',
    authDomain: 'utilitybills-c942a.firebaseapp.com',
    storageBucket: 'utilitybills-c942a.firebasestorage.app',
    measurementId: 'G-S0Z1MM7Z2R',
  );
}
